### ISSUE TITLE
Returns "Initial pattern not found"

### ISSUE THREAD

**Issue by sarabsethi** [w3slley/bookcover-api#24]
Hi,

First, very cool tool thanks for sharing! 

I had some luck playing with it earlier today, but now get a "{"error":"Initial pattern not found"}" return for any request I try, including the example in the readme. 

Am I doing something wrong, or is the service down?

Cheers!
Sarab

**Comment by jamesflores** [comment]
I got this too. It might be restricted. See my gist where I roll my own here: https://gist.github.com/jamesflores/85e9777d5ca076b2d29312a31754003e

**Comment by sarabsethi** [comment]
Ah nice, thanks. There's some magic in the original API which seems to give better results but I'll dig into it a bit further and see if I can use a hybrid solution

**Comment by w3slley** [comment]
Hey @sarabsethi. Maybe I can improve the error handling so that it's clearer as to what's happening. I'll also update the README with more details on how the API retrieves the images (it literally performs a google search for the book title and author name for the first Goodreads link and gets the image from the HTML Goodreads returns, nothing fancy). Either way, getting this error means something went wrong with the search.
I tried calling the sample request and it seems to be working now. Please let me know if it's still not working for you.

**Comment by himanshubanerji** [comment]
Getting the same issue here as well, this was working file few hours ago, not sure what broke it

**Comment by jamesflores** [comment]
I ended up making this into a wrapper: https://github.com/jamesflores/bookcover-generator-worker

**Comment by w3slley** [comment]
The fix was introduced [in this commit](https://github.com/w3slley/bookcover-api/commit/b2158d9908304e13698d049e101fe9a6cd23bf38). The issue in the end had to do with how the image retrieval was being made: an initial request was made to google (I know, not the best move) to retrieve the Goodreads book url. However, after some requests Google flagged the IP with bot validation and the API was no longer able to get the correct url. Searching directly in Goodreads website solves the issue.
